In [1]:
import numpy as np

In [41]:
class Perceptron:
    def __init__(self, dim):
        self.weight = [0.0 for _ in range(dim)]
        self.bias = 0.0
    def __str__(self):
        return "weight={}\nbias={}\n".format(self.weight, self.bias)
    def __forward(self, input):
        return np.dot(input, self.weight) + self.bias
    def __activation(self, x):
        #sigmod
        return 1 if element > 0 else 0
    def __update(self, input, output, label, learnig_rate):
        delta = np.subtract(label, output)
        for x, d in zip(input, delta):
            self.weight = np.add(self.weight, learnig_rate * d * x)
            self.bias += learnig_rate * d
            print(self.__str__())
    def predict(self, input):
        return self.__activation(self.__forward(input))
    def train(self, input, label, epochs, learnig_rate):
        for _ in range(epochs):
            print(self.__forward(input))
            output = self.predict(input)
            print(output)
            self.__update(input, output, label, learnig_rate)
            #print(self.__str__()) 


In [42]:
input = np.array([[1,1],[1,0],[0,0],[0,1]])
label = np.array([1,0,0,0])

pp = Perceptron(2)
pp.train(input, label, 1, 0.1)

[0. 0. 0. 0.]
[0, 0, 0, 0]
weight=[0.1 0.1]
bias=0.1

weight=[0.1 0.1]
bias=0.1

weight=[0.1 0.1]
bias=0.1

weight=[0.1 0.1]
bias=0.1



In [33]:
print(pp)

weight=[0.1 0.1]
bias=-0.1



In [5]:
a = [[1,2,3],[4,5,6]]
b = [1,2,3]
np.matmul(a, b)+[1]

array([15, 33])

In [44]:
b = np.array([1,2,3])
b*b

array([1, 4, 9])